baseurl = "https://robertmylesmcdonnell.netlify.com/"
preserveTaxonomyNames = true
paginate = 3
languageCode = "en-us"
title = "Robert Myles McDonnell"
theme = "hugo-future-imperfect"
googleAnalytics = "76482767"
disqusShortname = "rob-gitblog"
enableEmoji =  true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[params]
    # Sets the meta tag description, usually reserved for the main page
    description          = "Robert Myles McDonnell's website"
    # This will appear on the top left of the navigation bar
    navbarTitle          = "Home"
    # Social media buttons that appear on the sidebar
    socialAppearAtTop    = true
    socialAppearAtBottom = true
    # set this to the section name if section is not post
    viewMorePostLink     = "/post/"

    categoriesByCount    = true
    includeReadingTime   = true
    # The set of favicons used are based on the write-up from this link:
    # https://github.com/audreyr/favicon-cheat-sheet
    # Please see the favicon partial template for more information
    loadFavicon          = false
    faviconVersion       = ""

    # Load custom CSS or JavaScript files. This replaces the deprecated params
    # minifiedFilesCSS and minifiedFilesJS. The variable is an array so that you
    # can load multiple files if necessary. You can also load the standard theme
    # files by adding the value, "default".
    # customCSS            = ["default", "/path/to/file"]
    # customJS             = ["default", "/path/to/file"]

    # Loading min files for exampleSite
    customCSS            = ["/css/main.min.css"]
    customJS             = ["/js/main.min.js"]


    [params.logo]
        url = "logo.png"
        width = 50
        height = 50
        alt = "Logo"

    [params.intro]
        header    = "if(topic != junk) {write} else { wine }"
        paragraph = "by Robert Myles McDonnell"
        about     = ""


    [params.intro.pic]
        src       = "/images/pic1.jpg"
        # modify your picture in the shape of a circle or
        # future imperfect's hexagonal shape
        circle    = false
        imperfect = true
        width     = ""
        alt       = ""

    [params.postAmount]
        sidebar = 10

    [[menu.main]]
        name = "Blog"
        url = "/post/"
        identifier = "fa fa-newspaper-o"
        weight = 4

    [[menu.main]]
        name = "About"
        url = "/about/"
        weight = 5

    [[menu.main]]
        name = "Categories"
        url = "/categories/"
        weight = 6

    [[menu.main]]
        name = "Blogroll"
        url = "/blogroll/"
        weight = 7
        identifier = "fa fa-bookmark-o"

    [[menu.main]]
        name = "Other"
        url = "/other/"
        weight = 7
        identifier = "fa fa-music"

    [[menu.main]]
        name = "GitHub"
        url = "https://github.com/RobertMyles"
        identifier = "fa fa-code"
        weight = 2

    [[menu.main]]
        name = "Research"
        url = "/research/"
        identifier = "fa fa-bar-chart"
        weight = 1

    [[menu.main]]
        name = "CV"
        url = "/cv/"
        identifier = "fa fa-file-o"
        weight = 3

    [social]
        github          = "RobertMyles"
        linkedin        = "robert-mcdonnell-7475b320"
        stackoverflow   = "4296028/robertmc"
        facebook_admin  = "1213956375281226"
        twitter         = "RobertMylesMc"
        email           = "robertmylesmcdonnell@gmail.com"
        bitbucket       = ""
        jsfiddle        = ""
        codepen         = ""
        foursquare      = ""
        dribbble        = ""
        deviantart      = ""
        behance         = ""
        flickr          = ""
        instagram       = ""
        youtube         = ""
        vimeo           = ""
        vine            = ""
        medium          = ""
        wordpress       = ""
        tumblr          = ""
        xing            = ""
        slideshare      = ""
        reddit          = ""
        pinterest       = ""
        googleplus      = ""
        facebook        = ""
        twitter_domain  = ""
